### ISSUE TITLE
Why should I need to copy the files in /script/* to the kernel repo kernel/drivers/dax/ ?

### ISSUE THREAD

**Issue by Konna619** [robinlee09201/ctFS#1]
How does the file set_nvdimm.sh (in /script/) work in kernel repo?I don't understand what this copy behaviour means.

**Comment by robinlee09201** [comment]
It's to set up the app-direct mode of the Optane DC PMM.

**Comment by Konna619** [comment]
Thank you for your response.I know that script is to set up the PM.
I want to know since the script can be **executed** in its **original** path(/script/)，why it's needed to be **copyed** to **kernel** **repo** as **README** wrote?(Copy the files in **/script/*** to the kernel repo **kernel/drivers/dax/**)
