### ISSUE TITLE
ctFS could not run test programs

### ISSUE THREAD

**Issue by KeeningSunder** [robinlee09201/ctFS#2]
Hello,

When I was trying to evaluating the ctFS on my own machine, I was unable to launch test programs with `run_ctfs.sh` (e.g. `test/fstest`, or simple commands like `ls`).

I have retried installing ctFS several times. I also have tried to apply some fixes/play around the code by myself. But none of these efforts resolve the problem. It would be of great help if you can provide some hints for me. Thanks in advance.

### Step to reproduce:
- Perform `Kernel part source code`, `Compile` and `Configure` steps of ctFS README.
- Update the path in `test/run_ctfs.sh` to point to my compiled `libctfs.so` (changed to `LD_PRELOAD=<my_cloned_ctfs_folder>/bld/libctfs.so $@`).
- Execute `sudo script/run_ctfs.sh ls` or `sudo script/run_ctfs.sh test/fstest -a -p "\\/test"`
- Program crashed, error `segmentation fault`

### Observations:
- The assertion check for `CT_MAGIC` in `ctfs_func.c` failed when trying to execute programs, preventing them from starting. The `ct_super->magic` holds empty value.
https://github.com/robinlee09201/ctFS/blob/cb6d45599d4ac8ec57a5ce0c4a8c5f7a99cbae23/ctfs_func.c#L101
- Nether `sudo mkfs` nor `sudo mkfs 1` fix the assertion failure.
- Seems like only some header data has non-zero value. Magic, along with some others, are zeroed out when reading. This is checked by printing the values in `ct_super` at these two places and cross check the values:
https://github.com/robinlee09201/ctFS/blob/cb6d45599d4ac8ec57a5ce0c4a8c5f7a99cbae23/ctfs_func.c#L66-L68
https://github.com/robinlee09201/ctFS/blob/cb6d45599d4ac8ec57a5ce0c4a8c5f7a99cbae23/ctfs_func.c#L95-L96
- Each time I trying to launch a program with ctFS, exactly one `DAX INITIAL PAGE FAULT` line is added into `dmesg`. No other error, warning or message generated.

### If I remove the `ROBIN_PSWAP` define and recompile the kernel:
https://github.com/robinlee09201/ctFS/blob/cb6d45599d4ac8ec57a5ce0c4a8c5f7a99cbae23/kernel/dax-private.h#L11
- The previously written ctFS header can be successfully read. And the magic check succeed. No `mkfs` is executed between the changes. (It is also impossible to `mkfs` if `ROBIN_PSWAP` is not defined. A `SIGBUS` will be thrown)
- This could potentially means that the `mkfs` writes were succeed. But the reads in `ctfs_init` failed somehow.
- However, even with the valid header, under this setting, the program will still crash. (`ENOTDIR` in `inode_path2inode`) I do not assume it is a bug for now, just for your information.

### My environment:
- Ubuntu 20.04.5 with ctFS kernel (5.7-rc7)
- ndctl 67+
- Two optane pmem plugged, one of them is used for testing ctFS

**Comment by robinlee09201** [comment]
Hi Sunder,
Thank you so much for your feedback! I'm currently on vacation. Do you mind me checking back on the issue two weeks later?

**Comment by robinlee09201** [comment]
Hi Sunder,
Thank you so much for your feedback! I'm currently on vacation. Do you mind me checking back on the issue two weeks later?

**Comment by KeeningSunder** [comment]
Thanks for the respond! Please take your time and enjoy your vacation.

**Comment by KeeningSunder** [comment]
Hi, Robin. Do you have any updates on this issue?

**Comment by BOGEDABUDA** [comment]
> I have encountered the same issue as yours. The main cause is that  `dax_start()` fails to initialize the frame by using `ioctl(dax_fd, DAX_IOCTL_INIT, (uint64_t)frame);`.  So the keys of mpk are not allocated with `pkey_alloc()`, which triggers the segmentation faults.
> Currently, you can fix this bug in user space by doing as follows.

modify two functions in ctfs_func.c, `int ctfs_init(int flag){}` and `int ctfs_mkfs(int flag){}`
```C
  //   ct_rt.mpk[DAX_MPK_DEFAULT] = frame.mpk_default;
  //   ct_rt.mpk[DAX_MPK_FILE]    = frame.mpk_file;
  //   ct_rt.mpk[DAX_MPK_META]    = frame.mpk_meta;

  ct_rt.mpk[DAX_MPK_DEFAULT] = pkey_alloc(0, PKEY_DISABLE_WRITE);
  ct_rt.mpk[DAX_MPK_FILE]    = pkey_alloc(0, PKEY_DISABLE_WRITE);
  ct_rt.mpk[DAX_MPK_META]    = pkey_alloc(0, PKEY_DISABLE_WRITE);
  pkey_mprotect((void*)ct_rt.base_addr, MAP_SIZE, PROT_READ | PROT_WRITE,
                ct_rt.mpk[DAX_MPK_DEFAULT]);
```

**Comment by KeeningSunder** [comment]
@BOGEDABUDA Hi, very thanks for your hint! Sadly, the ctFS still does not work on our machine after applying it :(

**Comment by KeeningSunder** [comment]
Below are the written and read `ct_super` struct values from `ctfs_mkfs` and `ctfs_init` calls on our machine.

Written `ct_super`:
```
magic = "ctfs_v1\0\0"
first_pgg = 0x8000000000
page_used = 0x9000011080002
page_total = 0x0
alloc_prot_bmp = 0x400
lvl9_bmp = 0x800
root_inode = 0x8000011070002
padding = 0x0
inode_used = 0x0
inode_bmp_touched = 0x0
inode_hint = 0x0
alloc_prot_clock = 0x0
next_sub_lvl = 0x0
```

Read `ct_super`:
```
magic = "\0\0\0\0\0\0\0\0"
first_pgg = 0x8000000000
page_used = 0x9000011080002
page_total = 0x0
alloc_prot_bmp = 0x0
lvl9_bmp = 0x8000000000
root_inode = 0x8000011070002
padding = 0x0
inode_used = 0x0
inode_bmp_touched = 0x8000000020 
inode_hint = 0x7000011060002
alloc_prot_clock = 0x0
next_sub_lvl = 0x1
```

**Comment by BOGEDABUDA** [comment]
ctFS is working on a contigues memory region by mapping `/dev/dax0.0`. Considering the logic of `ctfs_init` is absolutely right, the mismatch of `ct_super` may be caused by mistakenly initializing the memory region. Maybe you can further check whether the `/dev/dax0.0` has been correctly created on your machine. And the mode of `/dev/dax0.0` should be readable and writeable for you.

**Comment by robinlee09201** [comment]
Thank you so much for replying, @BOGEDABUDA 
@KeeningSunder Do you mind trying to run mkfs with an argument? e.g. mkfs 1
I forgot to mention that mkfs will only rewrite everything with an argument. Otherwise, it only clears the persistent page table.

**Comment by KeeningSunder** [comment]
Thank you for your time @robinlee09201 @BOGEDABUDA. I have fixed the issue with some code tweaks. I **strongly** believe my code change is just a dirty hack, but anyway, it just works.

Here is my change and my thought process:

### Debug step

After some debug, I find that the ctFS header keeps being overwritten before leaving `ctfs_init` function. I find that the overwriting happens during the call to `memset` (L288) here:

https://github.com/robinlee09201/ctFS/blob/664a8b7941c8039a2c45783cc249aa32be1780c6/ctfs_pgg.c#L280-L294

During each iteration of the loop, four 64-bit values in the `ct_super` is being overwritten by `0 0 0 0`, and later assigned some other value:

```
address of ctFS header = 0x7dcfc5600000
intended value of ctFS header (as a series of 64-bit hex integer):
    31765f73667463 8000000000 9000011080002 0 400 800 1 0 2 8000 1 0 

memset(0x7e4fc5600000, 0, 32)
value of ctFS header, iter 1 before memset: 31765f73667463 8000000000 9000011080002 0 400 800 1 0 2 8000 1 0 
value of ctFS header, iter 1 after memset:  0 0 0 0 400 800 1 0 2 8000 1 0
value of ctFS header, iter 1 complete:      0 0 9000000080002 0 400 800 1 0 2 8000 1 0

memset(0x7e4fc5600020, 0, 32)
value of ctFS header, iter 2 before memset: 0 0 9000000080002 0 400 800 1 0 2 8000 1 0 
value of ctFS header, iter 2 after memset:  0 0 9000000080002 0 0 0 0 0 2 8000 1 0 
value of ctFS header, iter 2 complete:      0 0 9000000080002 0 0 8000000000 8000000070002 0 2 8000 1 0 

memset(0x7e4fc5600040, 0, 32)
value of ctFS header, iter 3 before memset: 0 0 9000000080002 0 0 8000000000 8000000070002 0 2 8000 1 0 
value of ctFS header, iter 3 after memset:  0 0 9000000080002 0 0 8000000000 8000000070002 0 0 0 0 0 
value of ctFS header, iter 3 complete:      0 0 9000000080002 0 0 8000000000 8000000070002 0 0 8000000020 7000000060002 0 

...
```

### My guess

I have double checked the virtual address of ctFS header and the PGG header array, they are different. But, it seems like they are mapped to the same physical address. I'm not sure how this happened, nor if it is intended or a bug.

I also find that the PGG header array is placed at the very beginning of the first PGG. So it is controlled by the `ct_super.first_pgg` field.

My guess is ctFS use some way to wrap the address so that you can accommodate a large address into a 128GB PMem. But since the `CT_OFFSET_1_PGG` is 512GB, and I am using a 512GB PMem, the first PGG is exactly wrapped to the location of the file system header, causing the overwrite.

### My fix

Anyway, since the value of `ct_super.first_pgg` decides where the first PGG is placed at, I can apply this one line patch here to move the location of first PGG and make ctFS work:

https://github.com/robinlee09201/ctFS/blob/664a8b7941c8039a2c45783cc249aa32be1780c6/ctfs_func.c#L59-L63

```c
// sb->first_pgg = CT_OFFSET_1_PGG;
sb->first_pgg = CT_OFFSET_1_PGG + CT_OFFSET_1_PGG / 2; // patched
```

With the patch applied, now I can run the workloads without any error.
